services:
  - type: web
    name: guestPro
    env: node
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Omidh:Omidhh12@guestmanager.e7c95uf.mongodb.net/?retryWrites=true&w=majority&appName=GuestManager
      - key: PORT
        value: 3000
    autoDeploy: true
